apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: myapp-server
spec:
  replicas: 1
  selector:
    app: myapp-server
    deploymentconfig: myapp-server
  template:
    metadata:
      labels:
        app: myapp-server
        deploymentconfig: myapp-server
    spec:
      containers:
        - image: 172.30.1.1:5000/sample-app/myapp-server
          name: myapp-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: myapp-redis-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: myapp-postgres-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
